program : pfspinstance.h flowshop.cpp pfspinstance.cpp

	g++ -O3 -c ./flowshop.cpp -o ../build-example/flowshop.o
	g++ -O3 -c ./pfspinstance.cpp -o ../build-example/pfspinstance.o

	g++ -O3 ../build-example/flowshop.o ../build-example/pfspinstance.o -o ../build-example/flowshopWCT

clean:
	rm ./*.o ../build-example/flowshopCWT
